name: sistem_parkir_flutter_offline_full
description: Sistem parkir offline (sqflite) + QR scan/print PDF + backup/restore
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Database
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.3

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.3

  # QR & Scanner
  mobile_scanner: ^5.1.1
  qr_flutter: ^4.1.0

  # Print / Export
  pdf: ^3.11.0
  printing: ^5.12.0
  share_plus: ^9.0.0
  file_picker: ^8.0.5
  permission_handler: ^11.3.1

  # Tambahan untuk Rekap (Export Excel + buka file)
  excel: ^4.0.1
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/